language: java

jdk:
 - oraclejdk8 
 
addons:
 -sonarqube: true
 
branches:
  only:
    - master
    - desenvolvimento
    
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=4d3569a1813b4d34df92dc574dbdd7989bedd2ae
  
  
   
