language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true

env:
  global:
  - secure: LJfmVXRVfGWK2U7cOLRsGkdSsgLOPuqvkSJdecyspiF/xn98bY6KQ5huY0VofEW36izdXS73XWjlUNYy2oy0j3HHs7Sq4IkSG3qmXkFMu6wYNpjX7+roCM9VcUjGkZfJVsfI1JQQNTN377GigzhtacGaPlp0JZDJThsDgyQhjTQ=


script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
